// SPDX-License-Identifier: Apache-2.0

//! Copper is generated by an external autorouter, never by Synth itself.
//!
//! Synth owns everything up to the copper: source parsing, topology,
//! placement, board/layer/net-class constraints, and the deterministic
//! export boundary. This crate owns everything after it: selecting a
//! routing engine, running it inside hard resource limits, and deciding
//! — independently of the router's own bookkeeping — whether what came
//! back may be called routed.
//!
//! The separation exists because a router's exit code is a claim, not a
//! result. FreeRouting exits `0` after routing nothing at all; KiCadRoutingTools
//! exits `0` while leaving open nets behind. Treating either as success is
//! how an empty board reaches a fabricator. So every candidate passes the
//! same downstream pipeline regardless of which engine produced it:
//!
//! 1. the un-routed export is retained as `<stem>.synth.kicad_pcb` and is
//!    never overwritten by a failed or partial run ([`RouteRequest::baseline`]);
//! 2. the engine runs with a wall-clock budget, an output cap, and an
//!    optional cancellation token ([`process`]);
//! 3. the candidate board is re-read from disk ([`pcb_read`]) rather than
//!    trusted, and checked against the baseline it was routed from;
//! 4. connectivity is re-derived from copper geometry — union-find over
//!    pads, tracks, and vias — never read from the router's own bookkeeping
//!    ([`validate::connectivity`]);
//! 5. zones are refilled and `kicad-cli pcb drc` runs against the resolved
//!    fabrication profile;
//! 6. only a candidate that survives all of that becomes [`RouteState::Routed`].
//!
//! Four terminal states stay distinct because they call for different human
//! responses: [`RouteState::Routed`], [`RouteState::ReviewRequired`],
//! [`RouteState::RouterUnavailable`], and [`RouteState::ValidationFailed`].
//! Collapsing any two of them — most dangerously treating an unavailable
//! router as a pass — is the failure mode this crate exists to prevent.
//!
//! Selection is explicit. If the chosen engine is missing, the run fails
//! with [`RouterFailureReason`] naming what to install; it never silently
//! falls back to another engine, and there is no built-in router to fall
//! back to.
//!
//! [`RouteRequest::baseline`]: RouteRequest::baseline_path

#![forbid(unsafe_code)]

pub mod capability;
pub mod contract;
pub mod drc;
pub mod escape;
pub mod failure;
pub mod freerouting;
pub mod kicad_routing_tools;
pub mod pcb_read;
pub mod process;
pub mod result;
pub mod validate;

use std::path::{Path, PathBuf};

pub use capability::{discover, RouterCapability};
pub use contract::{
    FabricationPolicy, FreeroutingOptions, KiCadRoutingToolsOptions, KrtEscalation, RouteRequest,
    RouterEngine, RouterLimits,
};
pub use failure::{RouterFailure, RouterFailureReason, RouterStage};
pub use result::{RouteReport, RouteState, RouteStatistics, RouterProvenance, ValidationSummary};
pub use validate::{
    validate_candidate, ConnectivityReport, FabricationVerdict, OpenConnection, TopologyReport,
};

/// Schema version stamped into every [`RouteReport`] this crate writes.
///
/// Part of the run-record contract: a consumer that cannot parse the
/// schema it expects should be able to see which one it got rather than
/// silently misread a field.
pub const ROUTE_REPORT_SCHEMA: &str = "synth.routing.v1";

/// Run `engine` over the board at [`RouteRequest::board_path`] and report
/// what came back.
///
/// This is the single entry point every surface (CLI, MCP, renderer, SaaS)
/// routes a board through, so the router identity and terminal state they
/// report cannot diverge between layers.
///
/// The returned [`RouteReport`] is written to
/// [`RouteRequest::report_path`] before this function returns, so a run
/// that fails is as auditable as one that succeeds.
pub fn route(request: &RouteRequest) -> RouteReport {
    // The duplicate-run guard is taken first. Reporting "router
    // unavailable" while a run is already writing this candidate would name
    // the wrong problem, and the operator would go looking for a missing
    // install that is not the issue.
    let _guard = match process::RunGuard::acquire(request.candidate_path().display().to_string()) {
        Ok(guard) => guard,
        Err(detail) => {
            let report = RouteReport::failed(
                request,
                &None,
                failure::RouterFailure::for_stage(
                    request.engine,
                    RouterStage::Route,
                    RouterFailureReason::SpawnFailed,
                    detail,
                ),
            );
            write_report(&report, request);
            return report;
        }
    };

    let capability = capability::discover(request);
    if let Some(failure) = capability.failure() {
        let mut report = RouteReport::unavailable(request, &Some(capability.clone()), failure);
        report.escape = escape::analyse_baseline(request);
        write_report(&report, request);
        return report;
    }

    let run = match request.engine {
        RouterEngine::Freerouting => freerouting::route(request),
        RouterEngine::KiCadRoutingTools => kicad_routing_tools::route(request),
    };

    let mut report = match run {
        Ok(candidate) => finalize(request, Some(&capability), candidate),
        Err(failure) => RouteReport::failed(request, &Some(capability), failure),
    };
    // A property of the design and the process, not of the attempt, so it is
    // reported whatever the run did — including when the engine was missing.
    report.escape = escape::analyse_baseline(request);
    write_report(&report, request);
    report
}

/// Reduce a design name to a filesystem-safe stem.
///
/// Shared with the exporter so run-record filenames line up with the
/// artifacts they describe, however the design was spelled.
#[must_use]
pub fn sanitize_stem(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for c in name.chars() {
        if c.is_ascii_alphanumeric() || c == '_' || c == '-' {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        "untitled".to_string()
    } else {
        out
    }
}

/// Best-effort write of the run record.
///
/// A report that cannot be written must not turn a routing outcome into a
/// different outcome: the caller still gets the in-memory verdict, and the
/// problem surfaces as a warning. Losing the verdict would be the worse
/// failure.
fn write_report(report: &RouteReport, request: &RouteRequest) {
    if let Err(error) = report.write_to(&request.report_path()) {
        eprintln!(
            "warning: routing run record could not be written to {}: {error}",
            request.report_path().display()
        );
    }
}

/// Promote a router-produced candidate into a report, installing it only if
/// it survives independent validation.
///
/// The ordering is the point. Validation reads the candidate from disk and
/// never consults the router's summary for connectivity, so a router that
/// over-reports its own success cannot promote itself. A candidate that
/// fails validation is still retained on disk as review material — it is
/// just never installed over the baseline.
fn finalize(
    request: &RouteRequest,
    capability: Option<&RouterCapability>,
    candidate: freerouting::Candidate,
) -> RouteReport {
    let verdict = validate_candidate(request, &candidate);

    let state = RouteReport::state_for_verdict(&verdict);

    // Only a validated candidate is allowed to become the delivered
    // board. `install` is a rename, so the baseline survives either way:
    // a rejected candidate is left on disk as review material, and the
    // delivered path still holds the un-routed export.
    if state.is_fabrication_ready() {
        if let Err(detail) = candidate.install(&request.board_path) {
            return RouteReport::failed(
                request,
                &capability.cloned(),
                RouterFailure::for_stage(
                    request.engine,
                    RouterStage::Install,
                    RouterFailureReason::Io,
                    format!("validated candidate could not be installed: {detail}"),
                ),
            );
        }
    }

    let mut statistics = candidate.statistics.clone();
    // The router's own open-net claim is kept for provenance, but the
    // connectivity pass is what fills the fields the report reports on.
    statistics.connected_nets = verdict.connectivity.connected_nets;
    statistics.open_nets = verdict.connectivity.open_nets;
    if statistics.open_net_names.is_empty() {
        statistics.open_net_names = verdict
            .connectivity
            .open
            .iter()
            .map(|o| o.net.clone())
            .collect();
    }

    RouteReport {
        schema_version: ROUTE_REPORT_SCHEMA.to_string(),
        state,
        engine: request.engine,
        capability: capability.cloned(),
        provenance: candidate.provenance,
        statistics,
        artifacts: candidate.artifacts,
        validation: Some(crate::result::ValidationSummary {
            fabrication_ready: verdict.fabrication_ready,
            topology: verdict.topology,
            connectivity: verdict.connectivity,
            kicad_drc: verdict.kicad_drc,
            blocking_reasons: verdict.blocking_reasons,
            unavailable_checks: verdict.unavailable_checks,
        }),
        failure: None,
        escape: Vec::new(),
    }
}

/// Write any serializable artifact to `path` as pretty JSON.
///
/// Used by callers that retain a specific artifact — a connectivity report,
/// say — alongside the run record, so every file in a run directory is
/// machine-readable rather than a mixture of JSON and prose.
pub fn write_artifact<T: serde::Serialize>(path: &Path, value: &T) -> std::io::Result<()> {
    write_json(path, value)
}

/// Write `report` to `path` as pretty JSON, returning whether it landed.
///
/// A report that cannot be written is not silently dropped: the caller
/// still returns the in-memory report, but the artifact set records
/// [`ArtifactPresence::Missing`](result::ArtifactPresence::Missing) so a
/// consumer comparing the two can tell the difference.
pub(crate) fn write_json<T: serde::Serialize>(path: &Path, value: &T) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let text = serde_json::to_string_pretty(value)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
    std::fs::write(path, text)
}

/// Resolve a helper script shipped in the repository's `tools/` directory.
///
/// Returns `None` rather than erroring when the tool is absent so that a
/// checkout without `tools/` reports "unavailable", which is actionable,
/// instead of an opaque I/O failure.
pub(crate) fn repo_tool(name: &str) -> Option<PathBuf> {
    let root = repo_root()?;
    let candidate = root.join("tools").join(name);
    candidate.is_file().then_some(candidate)
}

/// Best-effort repository root.
///
/// Prefers `CARGO_MANIFEST_DIR` (correct for a binary run out of a build
/// tree) and falls back to walking up from the current directory (correct
/// for an installed binary run inside a checkout).
pub(crate) fn repo_root() -> Option<PathBuf> {
    if let Ok(manifest) = std::env::var("CARGO_MANIFEST_DIR") {
        let path = PathBuf::from(manifest);
        if path.join("tools").is_dir() {
            return Some(path);
        }
        if let Some(up) = path.parent().and_then(Path::parent) {
            if up.join("tools").is_dir() {
                return Some(up.to_path_buf());
            }
        }
    }
    let mut dir = std::env::current_dir().ok()?;
    loop {
        if dir.join("tools").is_dir() && dir.join("registry").is_dir() {
            return Some(dir);
        }
        dir = dir.parent()?.to_path_buf();
    }
}
