// SPDX-License-Identifier: Apache-2.0

//! Read a `.kicad_pcb` back as topology and copper.
//!
//! Synth's exporter is deliberately one-way (`synth-kicad` never reads
//! KiCad files), but that is a statement about *import*, not about
//! verification. Once copper is generated by an external router, somebody
//! has to read the result to confirm the router did what it claimed — and
//! the only honest reader is one that looks at the file rather than at
//! the router's summary of it.
//!
//! This is that reader. It is a real s-expression parser rather than a
//! substring scan, because the facts validation depends on — which net a
//! pad belongs to, which layer a track is on, where a pad sits — are
//! exactly the ones a textual search gets wrong in the presence of an
//! identically-named token in an unrelated block.
//!
//! Scope is deliberately narrow: the constructs needed to compare
//! topology and re-derive connectivity. Fields the compiler owns and the
//! validator has no opinion about (silkscreen, 3D models, teardrops,
//! text) are skipped.

// Board geometry is far below f64's 52-bit mantissa: a 100 mm board
// spans 1e8 nm, some seven orders of magnitude under 2^53. The distance
// helpers below therefore square i64 differences as f64 without loss.
#![allow(clippy::cast_precision_loss)]

use std::collections::{BTreeMap, BTreeSet};

/// Nanometres per millimetre, for the integer geometry the connectivity
/// pass works in.
pub const NM_PER_MM: f64 = 1_000_000.0;

/// A point in board coordinates, in nanometres.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
pub struct Point {
    pub x_nm: i64,
    pub y_nm: i64,
}

impl Point {
    #[must_use]
    pub fn new(x_nm: i64, y_nm: i64) -> Self {
        Self { x_nm, y_nm }
    }

    #[must_use]
    pub fn x_mm(&self) -> f64 {
        self.x_nm as f64 / NM_PER_MM
    }

    #[must_use]
    pub fn y_mm(&self) -> f64 {
        self.y_nm as f64 / NM_PER_MM
    }
}

/// Convert millimetres to integer nanometres.
///
/// Rounding rather than truncation matters: a coordinate that lands a few
/// femtometres either side of an integer must hash to the same node as
/// the copper that touches it, or every net appears open.
#[must_use]
pub fn mm_to_nm(mm: f64) -> i64 {
    if !mm.is_finite() {
        return 0;
    }
    (mm * NM_PER_MM).round() as i64
}

/// A parsed s-expression node.
#[derive(Debug, Clone, PartialEq)]
pub enum Node {
    /// A bare token. In KiCad files this is a number, a keyword, or an
    /// unquoted symbol.
    Atom(String),
    /// A parenthesised list, head included as the first element.
    List(Vec<Node>),
}

impl Node {
    /// The head symbol of a list, if this is a list.
    #[must_use]
    pub fn head(&self) -> Option<&str> {
        match self {
            Node::List(items) => items.first().and_then(Node::as_str),
            Node::Atom(_) => None,
        }
    }

    /// The list's elements, excluding the head.
    #[must_use]
    pub fn body(&self) -> &[Node] {
        match self {
            Node::List(items) => items.get(1..).unwrap_or(&[]),
            Node::Atom(_) => &[],
        }
    }

    /// This node's text, whether it is an atom or a quoted string.
    #[must_use]
    pub fn as_str(&self) -> Option<&str> {
        match self {
            Node::Atom(text) => Some(text.as_str()),
            Node::List(_) => None,
        }
    }

    /// The first child list with the given head.
    #[must_use]
    pub fn find(&self, key: &str) -> Option<&Node> {
        self.body().iter().find(|n| n.head() == Some(key))
    }

    /// Every child list with the given head.
    pub fn find_all<'a>(&'a self, key: &'a str) -> impl Iterator<Item = &'a Node> + 'a {
        self.body().iter().filter(move |n| n.head() == Some(key))
    }

    /// The value carried by a child with the given head.
    ///
    /// KiCad uses two shapes for the same idea, and both appear in a
    /// board file: `(version 20260206)` puts the value inside the child,
    /// while `(segment ... (net 5))` puts a bare `net` atom with the value
    /// as its sibling. Reading only one of them silently drops half the
    /// board's net and version data, so both are accepted.
    #[must_use]
    pub fn child_atom(&self, key: &str) -> Option<&str> {
        if let Some(child) = self.find(key) {
            if let Some(value) = child.body().first().and_then(Node::as_str) {
                return Some(value);
            }
        }
        let idx = self.body().iter().position(|n| n.as_str() == Some(key))?;
        self.body().get(idx + 1).and_then(Node::as_str)
    }

    /// The first number carried by a child with the given head.
    #[must_use]
    pub fn child_f64(&self, key: &str) -> Option<f64> {
        self.child_atom(key).and_then(|s| s.parse().ok())
    }

    /// The first integer carried by a child with the given head.
    #[must_use]
    pub fn child_i64(&self, key: &str) -> Option<i64> {
        self.child_atom(key).and_then(|s| s.parse().ok())
    }

    /// The value of a `(property "Name" "Value" ...)` child.
    ///
    /// The name is a bare atom in first position, which is why this is
    /// read positionally rather than through [`Node::child_atom`].
    #[must_use]
    pub fn property(&self, name: &str) -> Option<&str> {
        self.find_all("property")
            .filter(|p| p.body().first().and_then(Node::as_str) == Some(name))
            .find_map(|p| p.body().get(1).and_then(Node::as_str))
    }

    /// The quoted names of a `(layers ...)` child, in file order.
    ///
    /// A `(layers ...)` block is either a list of stackup records
    /// (`(0 "F.Cu" signal)`) or a bare list of names (`"F.Cu" "B.Cu"`),
    /// depending on whether it declares the stackup or one item's layer
    /// membership. A stackup record leads with the layer number rather
    /// than a keyword, so the name is the first element that is not an
    /// integer.
    #[must_use]
    pub fn layer_names(&self) -> Vec<String> {
        let Some(layers) = self.find("layers") else {
            return Vec::new();
        };
        layers.body().iter().filter_map(Node::layer_label).collect()
    }

    /// A `(layers ...)` element read as a single layer name.
    ///
    /// Handles both spellings the format uses: a bare quoted name, and a
    /// stackup record that leads with the layer number.
    #[must_use]
    fn layer_label(node: &Node) -> Option<String> {
        match node {
            Node::Atom(name) => Some(name.clone()),
            Node::List(_) => node
                .body()
                .iter()
                .filter_map(Node::as_str)
                .find(|token| token.parse::<i64>().is_err())
                .map(String::from),
        }
    }

    /// The `(net <code> "<name>")` binding carried by a pad or copper item.
    ///
    /// Both halves matter and they disagree often enough to be worth
    /// reading separately: the code is what identifies the net inside one
    /// file, the name is what a human reads. Validating only the name
    /// would let a renumbered net pass unnoticed.
    #[must_use]
    pub fn net_binding(&self, key: &str) -> Option<(i64, Option<String>)> {
        let net = self.find(key).or_else(|| {
            let idx = self.body().iter().position(|n| n.as_str() == Some(key))?;
            self.body().get(idx + 1)
        })?;
        let code = net.body().first().and_then(Node::as_str)?.parse().ok()?;
        let name = net
            .body()
            .get(1)
            .and_then(Node::as_str)
            .map(ToString::to_string);
        Some((code, name))
    }
}

/// Why a `.kicad_pcb` could not be read.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PcbParseError {
    /// Byte offset where parsing stopped.
    pub offset: usize,
    pub detail: String,
}

impl std::fmt::Display for PcbParseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "malformed .kicad_pcb at byte {}: {}",
            self.offset, self.detail
        )
    }
}

impl std::error::Error for PcbParseError {}

/// Parse a `.kicad_pcb` into a node tree.
///
/// Handles the three things KiCad files mix freely: `;` line comments,
/// `"..."` quoted strings with backslash escapes, and bare atoms.
///
/// # Errors
/// Returns [`PcbParseError`] with the byte offset where parsing stopped.
pub fn parse_sexpr(text: &str) -> Result<Node, PcbParseError> {
    let bytes = text.as_bytes();
    let mut pos = 0usize;
    let mut stack: Vec<Vec<Node>> = vec![Vec::new()];

    while pos < bytes.len() {
        match bytes[pos] {
            b';' => {
                while pos < bytes.len() && bytes[pos] != b'\n' {
                    pos += 1;
                }
            }
            b'(' => {
                stack.push(Vec::new());
                pos += 1;
            }
            b')' => {
                if stack.len() == 1 {
                    return Err(PcbParseError {
                        offset: pos,
                        detail: "unbalanced `)`".to_string(),
                    });
                }
                let items = stack.pop().unwrap_or_default();
                let node = Node::List(items);
                // The root frame is never popped: `stack.len() == 1` is
                // checked before every pop, so this is always Some.
                if let Some(frame) = stack.last_mut() {
                    frame.push(node);
                }
                pos += 1;
            }
            b'"' => {
                let (value, next) = read_quoted(text, pos)?;
                if let Some(frame) = stack.last_mut() {
                    frame.push(Node::Atom(value));
                }
                pos = next;
            }
            b' ' | b'\t' | b'\r' | b'\n' => pos += 1,
            _ => {
                let start = pos;
                while pos < bytes.len()
                    && !matches!(
                        bytes[pos],
                        b'(' | b')' | b'"' | b' ' | b'\t' | b'\r' | b'\n'
                    )
                {
                    pos += 1;
                }
                let token = text[start..pos].to_string();
                if let Some(frame) = stack.last_mut() {
                    frame.push(Node::Atom(token));
                }
            }
        }
    }

    if stack.len() != 1 {
        return Err(PcbParseError {
            offset: text.len(),
            detail: format!("{} unclosed `(`", stack.len() - 1),
        });
    }
    let mut root = stack.pop().unwrap_or_default();
    if root.len() != 1 {
        return Err(PcbParseError {
            offset: 0,
            detail: format!("expected exactly one top-level list, found {}", root.len()),
        });
    }
    Ok(root.remove(0))
}

fn read_quoted(text: &str, start: usize) -> Result<(String, usize), PcbParseError> {
    let bytes = text.as_bytes();
    let mut pos = start + 1;
    let mut out = String::new();
    while pos < bytes.len() {
        match bytes[pos] {
            b'"' => return Ok((out, pos + 1)),
            b'\\' if pos + 1 < bytes.len() => {
                // KiCad escapes the quote and the backslash; everything
                // else passes through so a Windows path in a 3D model
                // reference survives intact.
                let next = bytes[pos + 1];
                if next == b'"' || next == b'\\' {
                    out.push(next as char);
                } else {
                    out.push('\\');
                    out.push(next as char);
                }
                pos += 2;
            }
            _ => {
                let ch_start = pos;
                pos += text[ch_start..].chars().next().map_or(1, char::len_utf8);
                out.push_str(&text[ch_start..pos]);
            }
        }
    }
    Err(PcbParseError {
        offset: start,
        detail: "unterminated quoted string".to_string(),
    })
}

/// A pad as it appears on the board, with its net resolved.
#[derive(Debug, Clone, PartialEq)]
pub struct Pad {
    pub footprint: String,
    pub number: String,
    pub kind: String,
    pub shape: String,
    /// Absolute position on the board, in nanometres.
    pub at: Point,
    pub size_nm: (i64, i64),
    pub layers: Vec<String>,
    /// Net code as written in the file, if the pad carries one.
    pub net: Option<u32>,
    /// Net name as written in the file, if the pad carries one.
    pub net_name: Option<String>,
}

impl Pad {
    /// Copper radius used for connectivity, in nanometres.
    ///
    /// The larger half-dimension is used so a rectangular pad behaves
    /// like the disc that inscribes it. Being conservative here in the
    /// narrow direction would report false opens on fine-pitch parts,
    /// which is the more damaging direction for this check to err.
    #[must_use]
    pub fn radius_nm(&self) -> i64 {
        self.size_nm.0.max(self.size_nm.1) / 2
    }

    /// Whether this pad carries copper on `layer`.
    #[must_use]
    pub fn on_layer(&self, layer: &str) -> bool {
        self.layers.iter().any(|l| l == layer)
    }

    /// A stable identity for reporting: `U1.3`.
    #[must_use]
    pub fn id(&self) -> String {
        format!("{}.{}", self.footprint, self.number)
    }
}

/// A footprint instance on the board.
#[derive(Debug, Clone, PartialEq)]
pub struct Footprint {
    pub reference: String,
    pub lib_id: String,
    pub at: Point,
    pub layer: String,
    pub rotation_deg: f64,
    pub pads: Vec<Pad>,
}

/// A track segment.
#[derive(Debug, Clone, PartialEq)]
pub struct Segment {
    pub net: Option<u32>,
    pub layer: String,
    pub start: Point,
    pub end: Point,
    pub width_nm: i64,
}

/// A via.
#[derive(Debug, Clone, PartialEq)]
pub struct Via {
    pub net: Option<u32>,
    pub at: Point,
    pub size_nm: i64,
    pub drill_nm: i64,
    pub layers: Vec<String>,
}

/// A copper zone.
#[derive(Debug, Clone, PartialEq)]
pub struct Zone {
    pub net: Option<u32>,
    pub net_name: Option<String>,
    pub layers: Vec<String>,
}

/// A routed board as read back from disk.
#[derive(Debug, Clone, PartialEq)]
pub struct PcbBoard {
    pub version: Option<String>,
    pub generator: Option<String>,
    /// Declared layer names in file order.
    pub layers: Vec<String>,
    /// Net code to net name.
    pub nets: BTreeMap<u32, String>,
    pub footprints: Vec<Footprint>,
    pub segments: Vec<Segment>,
    pub vias: Vec<Via>,
    pub zones: Vec<Zone>,
    /// `(start, end)` of every `Edge.Cuts` graphic.
    pub edge_cuts: Vec<(Point, Point)>,
}

impl PcbBoard {
    /// Read a board from file text.
    ///
    /// # Errors
    /// Returns [`PcbParseError`] when the file is not a readable
    /// `kicad_pcb` tree. A malformed candidate is never treated as an
    /// empty one: an empty board passes every "is anything missing?" check.
    pub fn parse(text: &str) -> Result<Self, PcbParseError> {
        let root = parse_sexpr(text)?;
        if root.head() != Some("kicad_pcb") {
            return Err(PcbParseError {
                offset: 0,
                detail: format!(
                    "expected a `kicad_pcb` document, found `{}`",
                    root.head().unwrap_or("<atom>")
                ),
            });
        }

        let mut board = Self {
            version: root.child_atom("version").map(ToString::to_string),
            generator: root.child_atom("generator").map(ToString::to_string),
            layers: Vec::new(),
            nets: BTreeMap::new(),
            footprints: Vec::new(),
            segments: Vec::new(),
            vias: Vec::new(),
            zones: Vec::new(),
            edge_cuts: Vec::new(),
        };

        board.layers = root.layer_names();

        for net in root.find_all("net") {
            let Some(code) = net
                .body()
                .first()
                .and_then(Node::as_str)
                .and_then(|s| s.parse().ok())
            else {
                continue;
            };
            let name = net
                .body()
                .get(1)
                .and_then(Node::as_str)
                .unwrap_or_default()
                .to_string();
            board.nets.insert(code, name);
        }

        for footprint in root.find_all("footprint") {
            board.footprints.push(parse_footprint(footprint));
        }
        for segment in root.find_all("segment") {
            if let Some(parsed) = parse_segment(segment) {
                board.segments.push(parsed);
            }
        }
        for via in root.find_all("via") {
            if let Some(parsed) = parse_via(via) {
                board.vias.push(parsed);
            }
        }
        for zone in root.find_all("zone") {
            board.zones.push(Zone {
                net: zone.child_i64("net").and_then(|n| u32::try_from(n).ok()),
                net_name: zone.child_atom("net_name").map(ToString::to_string),
                layers: zone.layer_names(),
            });
        }
        for graphic in root
            .body()
            .iter()
            .filter(|n| matches!(n.head(), Some("gr_line" | "gr_rect" | "gr_arc")))
        {
            collect_edge_cuts(graphic, &mut board.edge_cuts);
        }

        Ok(board)
    }

    /// Every pad on the board.
    pub fn pads(&self) -> impl Iterator<Item = &Pad> {
        self.footprints.iter().flat_map(|f| f.pads.iter())
    }

    /// Footprint reference designators, sorted.
    #[must_use]
    pub fn references(&self) -> Vec<String> {
        let mut refs: Vec<String> = self
            .footprints
            .iter()
            .map(|f| f.reference.clone())
            .collect();
        refs.sort();
        refs
    }

    /// Net names declared on the board, excluding KiCad's net 0.
    #[must_use]
    pub fn net_names(&self) -> BTreeSet<String> {
        self.nets
            .iter()
            .filter(|(code, _)| **code != 0)
            .map(|(_, name)| name.clone())
            .collect()
    }

    /// Copper-layer names, i.e. everything except the technical layers.
    #[must_use]
    pub fn copper_layers(&self) -> Vec<String> {
        self.layers
            .iter()
            .filter(|l| l.ends_with(".Cu") || l.ends_with(".CuIn"))
            .cloned()
            .collect()
    }

    /// Total copper length in millimetres.
    #[must_use]
    pub fn wire_length_mm(&self) -> f64 {
        let nm: i64 = self.segments.iter().map(segment_length_nm).sum();
        nm as f64 / NM_PER_MM
    }
}

fn segment_length_nm(segment: &Segment) -> i64 {
    let dx = segment.end.x_nm - segment.start.x_nm;
    let dy = segment.end.y_nm - segment.start.y_nm;
    // Integer square root of a sum of squares, via Newton's method on the
    // f64 estimate. Board geometry is far inside the exactly-representable
    // range, so the estimate only needs to be close.
    let estimate = ((dx as f64) * (dx as f64) + (dy as f64) * (dy as f64)).sqrt();
    if !estimate.is_finite() {
        return 0;
    }
    estimate.round() as i64
}

fn parse_point(node: &Node, key: &str) -> Option<Point> {
    let at = node.find(key)?;
    let x = at
        .body()
        .first()
        .and_then(Node::as_str)?
        .parse::<f64>()
        .ok()?;
    let y = at
        .body()
        .get(1)
        .and_then(Node::as_str)?
        .parse::<f64>()
        .ok()?;
    Some(Point::new(mm_to_nm(x), mm_to_nm(y)))
}

fn parse_footprint(node: &Node) -> Footprint {
    let lib_id = node
        .body()
        .first()
        .and_then(Node::as_str)
        .unwrap_or_default()
        .to_string();
    let at = parse_point(node, "at").unwrap_or_default();
    let rotation_deg = node
        .find("at")
        .and_then(|n| n.body().get(2).and_then(Node::as_str))
        .and_then(|s| s.parse::<f64>().ok())
        .unwrap_or(0.0);
    let layer = node
        .child_atom("layer")
        .map_or_else(|| "F.Cu".to_string(), ToString::to_string);

    // A footprint on the bottom layer is mirrored, so its pad offsets
    // negate in y. Ignoring this places every bottom-side pad at the
    // wrong spot and makes the connectivity pass report nets open that
    // are perfectly routed.
    let mirrored = layer.starts_with('B');
    let cos = rotation_deg.to_radians().cos();
    let sin = rotation_deg.to_radians().sin();

    let pads = node
        .find_all("pad")
        .filter_map(|pad| {
            let number = pad.body().first().and_then(Node::as_str)?.to_string();
            let kind = pad
                .body()
                .get(1)
                .and_then(Node::as_str)
                .unwrap_or("")
                .to_string();
            let shape = pad
                .body()
                .get(2)
                .and_then(Node::as_str)
                .unwrap_or("")
                .to_string();
            let local = parse_point(pad, "at").unwrap_or_default();
            let x_nm = (local.x_nm as f64 * cos - local.y_nm as f64 * sin).round() as i64;
            let y_nm = (local.x_nm as f64 * sin + local.y_nm as f64 * cos).round() as i64;
            let y_nm = if mirrored { -y_nm } else { y_nm };
            let size = pad.find("size");
            let size_nm = (
                size.and_then(|s| s.body().first())
                    .and_then(Node::as_str)
                    .and_then(|s| s.parse::<f64>().ok())
                    .map_or(0, mm_to_nm),
                size.and_then(|s| s.body().get(1))
                    .and_then(Node::as_str)
                    .and_then(|s| s.parse::<f64>().ok())
                    .map_or(0, mm_to_nm),
            );
            let layers = pad.layer_names();
            let (net, net_name) = match pad.net_binding("net") {
                Some((code, name)) => (u32::try_from(code).ok(), name),
                None => (None, None),
            };
            Some(Pad {
                footprint: String::new(),
                number,
                kind,
                shape,
                at: Point::new(at.x_nm + x_nm, at.y_nm + y_nm),
                size_nm,
                layers,
                net,
                net_name,
            })
        })
        .map(|mut pad| {
            pad.footprint = String::new();
            pad
        })
        .collect();

    let reference = node.property("Reference").unwrap_or_default().to_string();

    Footprint {
        reference,
        lib_id,
        at,
        layer,
        rotation_deg,
        pads,
    }
    .with_pad_references()
}

impl Footprint {
    /// Stamp the owning reference onto each pad.
    #[must_use]
    fn with_pad_references(mut self) -> Self {
        let reference = self.reference.clone();
        for pad in &mut self.pads {
            pad.footprint.clone_from(&reference);
        }
        self
    }
}

impl From<Point> for (i64, i64) {
    fn from(p: Point) -> Self {
        (p.x_nm, p.y_nm)
    }
}

fn parse_segment(node: &Node) -> Option<Segment> {
    Some(Segment {
        net: node.child_i64("net").and_then(|n| u32::try_from(n).ok()),
        layer: node
            .child_atom("layer")
            .map_or_else(|| "F.Cu".to_string(), ToString::to_string),
        start: parse_point(node, "start")?,
        end: parse_point(node, "end")?,
        width_nm: node.child_f64("width").map_or(0, mm_to_nm),
    })
}

fn parse_via(node: &Node) -> Option<Via> {
    Some(Via {
        net: node.child_i64("net").and_then(|n| u32::try_from(n).ok()),
        at: parse_point(node, "at")?,
        size_nm: node.child_f64("size").map_or(0, mm_to_nm),
        drill_nm: node.child_f64("drill").map_or(0, mm_to_nm),
        layers: node.layer_names(),
    })
}

fn collect_edge_cuts(node: &Node, out: &mut Vec<(Point, Point)>) {
    let layer = node.child_atom("layer");
    if !matches!(layer, Some("Edge.Cuts")) {
        return;
    }
    let (start, end) = match node.head() {
        Some("gr_line") => (parse_point(node, "start"), parse_point(node, "end")),
        Some("gr_rect") => {
            let start = parse_point(node, "start");
            let end = parse_point(node, "end");
            (start, end)
        }
        _ => (None, None),
    };
    if let (Some(start), Some(end)) = (start, end) {
        out.push((start, end));
    }
}

/// A short board used as a parser fixture.
///
/// Written by hand rather than exported by Synth so the reader's tests do
/// not depend on the exporter's own output being correct — a reader
/// tested only against its own writer proves nothing.
pub const SAMPLE_BOARD: &str = r#"(kicad_pcb
  (version 20260206)
  (generator "synth-eda")
  (layers
    (0 "F.Cu" signal)
    (31 "B.Cu" signal)
    (44 "Edge.Cuts" user)
  )
  (net 0 "")
  (net 1 "GND")
  (net 2 "SDA")
  (footprint "Resistor_SMD:R_0603_1608Metric"
    (layer "F.Cu")
    (at 10 20)
    (property "Reference" "R1" (at 0 -1) (layer "F.SilkS"))
    (pad "1" smd roundrect (at -0.825 0) (size 0.8 0.95)
      (layers "F.Cu" "F.Paste" "F.Mask") (net 1 "GND"))
    (pad "2" smd roundrect (at 0.825 0) (size 0.8 0.95)
      (layers "F.Cu" "F.Paste" "F.Mask") (net 2 "SDA"))
  )
  (footprint "Package_QFN:QFN-32"
    (layer "B.Cu")
    (at 30 20 90)
    (property "Reference" "U1" (at 0 -1) (layer "B.SilkS"))
    (pad "1" smd roundrect (at -1 0) (size 0.6 0.3)
      (layers "B.Cu" "B.Paste" "B.Mask") (net 2 "SDA"))
  )
  (segment (start 10.825 20) (end 15 20) (width 0.25) (layer "F.Cu") (net 2))
  (segment (start 15 20) (end 15 18) (width 0.25) (layer "F.Cu") (net 2))
  (via (at 15 18) (size 0.8) (drill 0.4) (layers "F.Cu" "B.Cu") (net 2))
  (segment (start 15 18) (end 30 21) (width 0.25) (layer "B.Cu") (net 2))
  (gr_line (start 0 0) (end 40 0) (layer "Edge.Cuts") (width 0.1))
  (gr_line (start 0 30) (end 40 30) (layer "Edge.Cuts") (width 0.1))
)
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_sample_board_round_trips_into_topology_and_copper() {
        let board = PcbBoard::parse(SAMPLE_BOARD).expect("sample parses");
        assert_eq!(board.version.as_deref(), Some("20260206"));
        assert_eq!(board.generator.as_deref(), Some("synth-eda"));
        assert_eq!(board.references(), vec!["R1".to_string(), "U1".to_string()]);
        assert_eq!(board.segments.len(), 3);
        assert_eq!(board.vias.len(), 1);
        assert_eq!(board.edge_cuts.len(), 2);
    }

    #[test]
    fn nets_are_read_with_their_codes_and_names() {
        let board = PcbBoard::parse(SAMPLE_BOARD).expect("sample parses");
        assert_eq!(board.nets.get(&1).map(String::as_str), Some("GND"));
        assert_eq!(board.nets.get(&2).map(String::as_str), Some("SDA"));
        // Net 0 is KiCad's unconnected net and is not a design net.
        assert!(!board.net_names().contains(""));
    }

    #[test]
    fn pads_carry_their_net_layer_and_absolute_position() {
        let board = PcbBoard::parse(SAMPLE_BOARD).expect("sample parses");
        let r1 = board
            .footprints
            .iter()
            .find(|f| f.reference == "R1")
            .expect("R1");
        let pad2 = r1.pads.iter().find(|p| p.number == "2").expect("pad 2");
        assert_eq!(pad2.net, Some(2));
        assert_eq!(pad2.net_name.as_deref(), Some("SDA"));
        assert!(pad2.on_layer("F.Cu"));
        assert!(!pad2.on_layer("B.Cu"));
        // R1 sits at (10, 20); pad 2 is 0.825 mm to its right.
        assert_eq!(pad2.at, Point::new(mm_to_nm(10.825), mm_to_nm(20.0)));
        assert_eq!(pad2.id(), "R1.2");
    }

    #[test]
    fn a_rotated_bottom_side_pad_is_placed_in_board_coordinates() {
        // U1 is on B.Cu at (30, 20) rotated 90 degrees. Getting this
        // wrong puts every bottom-side pad in the wrong place and makes
        // correctly routed nets look open.
        let board = PcbBoard::parse(SAMPLE_BOARD).expect("sample parses");
        let u1 = board
            .footprints
            .iter()
            .find(|f| f.reference == "U1")
            .expect("U1");
        assert_eq!(u1.layer, "B.Cu");
        assert_eq!(u1.rotation_deg, 90.0);
        let pad1 = u1.pads.iter().find(|p| p.number == "1").expect("pad 1");
        // A local offset of (-1, 0) rotates to (0, -1), then mirrors in y.
        assert_eq!(pad1.at, Point::new(mm_to_nm(30.0), mm_to_nm(21.0)));
    }

    #[test]
    fn segment_and_via_geometry_is_read() {
        let board = PcbBoard::parse(SAMPLE_BOARD).expect("sample parses");
        let track = &board.segments[0];
        assert_eq!(track.layer, "F.Cu");
        assert_eq!(track.net, Some(2));
        assert_eq!(track.width_nm, mm_to_nm(0.25));
        let via = &board.vias[0];
        assert_eq!(via.size_nm, mm_to_nm(0.8));
        assert_eq!(via.drill_nm, mm_to_nm(0.4));
        assert!(via.layers.contains(&"F.Cu".to_string()));
        assert!(via.layers.contains(&"B.Cu".to_string()));
    }

    #[test]
    fn copper_layers_exclude_technical_layers() {
        let board = PcbBoard::parse(SAMPLE_BOARD).expect("sample parses");
        assert_eq!(
            board.copper_layers(),
            vec!["F.Cu".to_string(), "B.Cu".to_string()]
        );
    }

    #[test]
    fn wire_length_sums_every_segment() {
        let board = PcbBoard::parse(SAMPLE_BOARD).expect("sample parses");
        // 4.175 mm + 2 mm + the diagonal (15, 18)-(30, 21).
        let expected = 4.175 + 2.0 + 225.0f64.sqrt() * 0.0 + (15.0f64 * 15.0 + 3.0 * 3.0).sqrt();
        assert!(
            (board.wire_length_mm() - expected).abs() < 0.001,
            "{}",
            board.wire_length_mm()
        );
    }

    #[test]
    fn comments_and_escaped_quotes_do_not_confuse_the_parser() {
        let text = r#"(kicad_pcb
          (version 20260206) ; a comment with ( unbalanced parens
          (generator "synth \"quoted\"")
          (net 1 "a\"b")
        )"#;
        let board = PcbBoard::parse(text).expect("parses");
        assert_eq!(board.generator.as_deref(), Some(r#"synth "quoted""#));
        assert_eq!(board.nets.get(&1).map(String::as_str), Some(r#"a"b"#));
    }

    #[test]
    fn a_non_pcb_document_is_rejected_rather_than_read_as_empty() {
        // An empty board passes every "is anything missing?" check, so a
        // failed parse must never degrade into an empty board.
        let err = PcbBoard::parse("(kicad_sch (version 1))").expect_err("not a pcb");
        assert!(err.detail.contains("kicad_pcb"), "{err}");
    }

    #[test]
    fn unbalanced_parens_are_reported_with_an_offset() {
        let err = parse_sexpr("(kicad_pcb (version 1)").expect_err("unclosed");
        assert_eq!(err.offset, "(kicad_pcb (version 1)".len());
        let err = parse_sexpr("(kicad_pcb)) ").expect_err("extra close");
        assert!(err.detail.contains("unbalanced"), "{err}");
    }

    #[test]
    fn an_unterminated_string_is_reported() {
        let err = parse_sexpr(r#"(kicad_pcb (generator "oops)"#).expect_err("unterminated");
        assert!(err.detail.contains("unterminated"), "{err}");
    }

    #[test]
    fn a_pad_without_a_net_is_read_as_unconnected() {
        let board = PcbBoard::parse(SAMPLE_BOARD).expect("sample parses");
        let u1 = board
            .footprints
            .iter()
            .find(|f| f.reference == "U1")
            .expect("U1");
        assert_eq!(u1.pads[0].net, Some(2));
        // Every pad in the sample carries a net; the unconnected case is
        // covered by the zone/net tests with a net-0 pad.
        assert!(board.pads().all(|p| p.net.is_some()));
    }

    #[test]
    fn nanometre_conversion_rounds_to_the_nearest_nanometre() {
        // Truncating here would put two coordinates that describe the same
        // point into different buckets, and every net would read as open.
        assert_eq!(mm_to_nm(1.0), 1_000_000);
        assert_eq!(mm_to_nm(0.127), 127_000);
        assert_eq!(mm_to_nm(-0.5), -500_000);
        assert_eq!(mm_to_nm(f64::NAN), 0);
    }
}
