version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    groups:
      gh-dependency:
        patterns:
          - "*"
    ignore:
      - dependency-name: "dtolnay/rust-toolchain"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    groups:
      cargo-dependency:
        patterns:
          - "*"
